name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Configure problem matchers for C++ build errors and warnings.
      - name: Setup Problem Matchers
        uses: Trass3r/setup-cpp@master

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Python Packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO Data
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build
        run: pio run

      # - name: Archive Firmware
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: firmware
      #     path: .pio/build/main/firmware.bin
      #     if-no-files-found: error

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: .pio/build/main/firmware.bin

  clang-format:
    name: Check Code Formatting
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Code Formatting
        uses: DoozyX/clang-format-lint-action@v0.11
        with:
          source: src
          clangFormatVersion: 11
